package com.stdplatform.gui_selector.Constant.XML;

public class XML_GEN {

	public static final String BEFORE_COMP = "<Window xmlns:my21=\"clr-namespace:VirtualBench.Sources.CustomControls.Generic.Oscilloscope.Core\"  x:Class=\"VirtualBench.Framework.VirtualBenchMain\"\n"
			+ "    xmlns=\"http://schemas.microsoft.com/winfx/2006/xaml/presentation\"\n"
			+ "    xmlns:x=\"http://schemas.microsoft.com/winfx/2006/xaml\"\n"
			+ "    Title=\"Virtual Bench\"\n"
			+ "    Loaded=\"Window_Loaded\" Closing=\"Window_Closing\"  ResizeMode=\"NoResize\"\n"
			+ "    WindowStartupLocation=\"CenterScreen\" xmlns:my=\"clr-namespace:VirtualBench.Framework\"  xmlns:my2=\"clr-namespace:WpfGauge;assembly=WpfGauge\" xmlns:my3=\"clr-namespace:CircularGauge;assembly=CircularGauge\" xmlns:my4=\"clr-namespace:VirtualBench.Sources.CustomControls.HMI.LED.Core\" xmlns:my5=\"clr-namespace:VirtualBench.Sources.CustomControls.Actuators.Stepper.Core\" xmlns:my6=\"clr-namespace:VirtualBench.Sources.CustomControls.Actuators.DCMotor.Core\" xmlns:my7=\"clr-namespace:VirtualBench.Sources.CustomControls.Sensors.AnalogInput.Core\" xmlns:my8=\"clr-namespace:VirtualBench.Sources.CustomControls.HMI.Encoder.Core\" xmlns:my9=\"clr-namespace:VirtualBench.Sources.CustomControls.HMI.PWM_Viewer.Core\" Unloaded=\"Window_Unloaded\" Closed=\"Window_Closed\" WindowStyle=\"SingleBorderWindow\" xmlns:my10=\"clr-namespace:VirtualBench.Sources.CustomControls.HMI.Touch.Core\" xmlns:my11=\"clr-namespace:VirtualBench.Sources.CustomControls.HMI.TFT.Core\"\n"
			+ "        xmlns:VBLed=\"clr-namespace:VirtualBench.Sources.CustomControls.HMI.LED.Core\" xmlns:my1=\"clr-namespace:VirtualBench.Sources.CustomControls.Generic.Switch.Core\" xmlns:my12=\"clr-namespace:VirtualBench.Sources.CustomControls.Sensors.Potentiometer.Core\" xmlns:my13=\"clr-namespace:VirtualBench.Sources.CustomControls.HMI.DOWD.Core\" xmlns:my14=\"clr-namespace:VirtualBench.Sources.CustomControls.HMI.EncoderGrayCode.Core\" xmlns:my15=\"clr-namespace:VirtualBench.Sources.CustomControls.Actuators.Relay.Core\" xmlns:my16=\"clr-namespace:VirtualBench.Sources.CustomControls.Actuators.Compressor.Core\" xmlns:my17=\"clr-namespace:VirtualBench.Sources.CustomControls.Generic.Variants.Core\" xmlns:my18=\"clr-namespace:VirtualBench.Sources.CustomControls.Actuators.Haptic.Core\" xmlns:my19=\"clr-namespace:VirtualBench.Sources.CustomControls.Common\" xmlns:my20=\"clr-namespace:VirtualBench.Sources.CustomControls.Actuators.Fan.Core\" DataContext=\"{Binding ElementName=dOWD1}\" Name=\"VBMainWindow\" xmlns:my22=\"clr-namespace:VirtualBench.Sources.CustomControls.Actuators.Blower.Core\" xmlns:my23=\"clr-namespace:VirtualBench.Sources.CustomControls.Generic.EEPROM.Core\" xmlns:my24=\"clr-namespace:VirtualBench.Sources.CustomControls.HMI.LCD.Core\" xmlns:my25=\"clr-namespace:VirtualBench.Sources.CustomControls.HMI.HUDImage.Core\" xmlns:my26=\"clr-namespace:VirtualBench.Sources.CustomControls.Custom.HUDImage.Header\"\n"
			+ "		MinHeight=\"0\"\n"
			+ "		MaxHeight=\"750\"\n"
			+ "		MaxWidth=\"1300\" \n"
			+ "		mc:Ignorable=\"d\" xmlns:d=\"http://schemas.microsoft.com/expression/blend/2008\" xmlns:mc=\"http://schemas.openxmlformats.org/markup-compatibility/2006\"\n"
			+ "		d:DesignHeight=\"750\"\n"
			+ "		d:DesignWidth=\"1300\" \n"
			+ "		SizeToContent=\"WidthAndHeight\">\n"
			+ "    <Grid Width=\"1282\" Height=\"712\" >\n"
			+ "        <Menu Height=\"24\" Name=\"menu1\" VerticalAlignment=\"Top\">\n"
			+ "            <Menu.Background>\n"
			+ "                <LinearGradientBrush EndPoint=\"0.504,1.5\" StartPoint=\"0.504,0.03\">\n"
			+ "                    <GradientStop Color=\"#00DDDDDD\" Offset=\"0\"/>\n"
			+ "                    <GradientStop Color=\"#AAAAAAAA\" Offset=\"0.567\"/>\n"
			+ "                </LinearGradientBrush>\n"
			+ "            </Menu.Background>\n"
			+ "            <MenuItem Header=\"Main\" InputGestureText=\"\" Name=\"MenuFile\" VerticalAlignment=\"Top\">\n"
			+ "                <MenuItem Header=\"Configuration\" Click=\"MenuItem_Configuration_Click\">\n"
			+ "                    <MenuItem.Icon>\n"
			+ "                        <Image Source=\"/Resources/Gears.gif\"\n"
			+ "                               Width=\"16\"\n"
			+ "                               Height=\"16\"\n"
			+ "                               HorizontalAlignment=\"Center\"\n"
			+ "                               />\n"
			+ "                    </MenuItem.Icon>\n"
			+ "                </MenuItem>\n"
			+ "                <MenuItem Header=\"Reset Bench\" Click=\"MenuItem_Click_1\">\n"
			+ "                    <MenuItem.Icon>\n"
			+ "                        <Image Source=\"/Resources/Reload.gif\" SnapsToDevicePixels=\"False\" ClipToBounds=\"False\" Stretch=\"None\"  Grid.IsSharedSizeScope=\"False\" HorizontalAlignment=\"Center\" VerticalAlignment=\"Center\"></Image>\n"
			+ "                    </MenuItem.Icon>\n"
			+ "                </MenuItem>\n"
			+ "                <MenuItem Header=\"Exit\" Click=\"MenuItem_Click_2\">\n"
			+ "                    <MenuItem.Icon>\n"
			+ "                        <Image Source=\"/Resources/Close.gif\" SnapsToDevicePixels=\"False\" ClipToBounds=\"False\" Stretch=\"None\"  Grid.IsSharedSizeScope=\"False\" HorizontalAlignment=\"Center\" VerticalAlignment=\"Center\"></Image>\n"
			+ "                    </MenuItem.Icon>\n"
			+ "                </MenuItem>\n"
			+ "            </MenuItem>\n"
			+ "            <MenuItem Header=\"Tools\">\n"
			+ "                <MenuItem Header=\"Numerical Converter + Checksum\" Click=\"MenuItem_Click_3\">\n"
			+ "                    <MenuItem.Icon>\n"
			+ "                        <Image Source=\"/Resources/Hex_Small.png\"\n"
			+ "                               Width=\"16\"\n"
			+ "                               Height=\"16\"\n"
			+ "                               HorizontalAlignment=\"Center\"\n"
			+ "                               >\n"
			+ "                        </Image>\n"
			+ "                    </MenuItem.Icon>\n"
			+ "                </MenuItem>\n"
			+ "                <MenuItem Header=\"Stopwatch\" Click=\"MenuItem_Click_4\">\n"
			+ "                    <MenuItem.Icon>\n"
			+ "                        <Image Source=\"/Resources/Stopwatch.png\" \n"
			+ "                               Width=\"16\"\n"
			+ "                               Height=\"16\"\n"
			+ "                               HorizontalAlignment=\"Center\"\n"
			+ "                               >\n"
			+ "                        </Image>\n"
			+ "                    </MenuItem.Icon>\n"
			+ "                </MenuItem>\n"
			+ "                <MenuItem Header=\"Calculator\" Click=\"MenuItem_Click_5\">\n"
			+ "                    <MenuItem.Icon>\n"
			+ "                        <Image Source=\"/Resources/Calculator.gif\"\n"
			+ "                               Width=\"16\"\n"
			+ "                               Height=\"16\"\n"
			+ "                               HorizontalAlignment=\"Center\"\n"
			+ "                               >\n"
			+ "                        </Image>\n"
			+ "                    </MenuItem.Icon>\n"
			+ "                </MenuItem>\n"
			+ "            </MenuItem>|\n"
			+ "            <MenuItem Header=\"VTP Design\" HorizontalAlignment=\"Stretch\" SnapsToDevicePixels=\"False\" VerticalContentAlignment=\"Top\" VerticalAlignment=\"Top\" Click=\"MenuItem_Click\">\n"
			+ "                <MenuItem.Icon>\n"
			+ "                    <Image Width=\"16\" Height=\"16\" Margin=\"0,0,-8,0\" Source=\"/VirtualBench;component/Resources/Execute.gif\" />\n"
			+ "                </MenuItem.Icon>\n"
			+ "            </MenuItem>\n"
			+ "\n"
			+ "            <MenuItem Header=\"Help\" VerticalAlignment=\"Top\">\n"
			+ "                <MenuItem Header=\"About Us\" Click=\"MenuItem_Click_7\">\n"
			+ "                    <MenuItem.Icon>\n"
			+ "                        <Image Source=\"/Resources/About_Us.png\"\n"
			+ "                               Width=\"16\"\n"
			+ "                               Height=\"16\"\n"
			+ "                               HorizontalAlignment=\"Center\"\n"
			+ "                               >\n"
			+ "                        </Image>\n"
			+ "                    </MenuItem.Icon>\n"
			+ "                </MenuItem>\n"
			+ "                <Separator></Separator>\n"
			+ "                <MenuItem Header=\"I Found a Bug! :)\" Click=\"MenuItem_Click_6\">\n"
			+ "                    <MenuItem.Icon>\n"
			+ "                        <Image Source=\"/Resources/Happy_Face.png\"\n"
			+ "                               Width=\"16\"\n"
			+ "                               Height=\"16\"\n"
			+ "                               HorizontalAlignment=\"Center\"\n"
			+ "                               >\n"
			+ "                        </Image>\n"
			+ "                    </MenuItem.Icon>\n"
			+ "                </MenuItem>\n"
			+ "            </MenuItem>\n"
			+ "        </Menu>";

	public static final String AFTER_COMP = "</Grid>\n"
			+ "    <Window.Background>\n" + "        <RadialGradientBrush>\n"
			+ "            <GradientStop Color=\"White\" Offset=\"0\" />\n"
			+ "            <GradientStop Color=\"#FFB4B4B4\" Offset=\"1\" />\n"
			+ "            <GradientStop Color=\"White\" Offset=\"0\" />\n"
			+ "        </RadialGradientBrush>\n" + "    </Window.Background>\n"
			+ "</Window>";

}
